#!/bin/bash
WORKSPACE=/Users/norm/411/code/workspace
PROJECT=assignment2
ECLIPSE=/Applications/eclipse-juno
CLASSPATH=$WORKSPACE/$PROJECT/bin:$ECLIPSE/plugins/org.junit_4.10.0.v4_10_0_v20120426-0900/junit.jar:$ECLIPSE/plugins/org.hamcrest.core_1.1.0.v20090501071000.jar 
export CLASSPATH
echo "Program: $2"
cat $2
echo ""
pass=$1
case $pass in
    ([Pp]ar*)
	pass=Parser  ;;
    (*)
	echo "Don't understand $pass";
	exit 1;;
esac
java driver.D$pass $2
